### ISSUE TITLE
erasing chats quite easy on Yottagram...

### ISSUE THREAD

**Issue by yusssufff** [Michal-Szczepaniak/Yottagram#17]
The options to erase chats (even if there is a remorse timer), are quite present in Yottagram...
There are quite many possibilities to erase a chat my mistake (if you write a too long message and try to scroll up to read it, you often end up clicking on the pulley "erase history").
Is that a developpement choice (the wish of easily erasing history or chats)?
Or could it be made harder than one single step to erase a chat?

**Comment by Michal-Szczepaniak** [comment]
There is remorse and thats perfectly enough.
